//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//


#ifndef CIRCT_DIALECT_RTLIL_RTLIL_TD
#define CIRCT_DIALECT_RTLIL_RTLIL_TD

include "circt/Dialect/RTLIL/RTLILDialect.td"
include "circt/Dialect/RTLIL/RTLILEnums.td"
include "circt/Dialect/RTLIL/RTLILTypes.td"
include "circt/Dialect/RTLIL/RTLILAttributes.td"
include "circt/Dialect/RTLIL/RTLILOpInterfaces.td"
include "circt/Dialect/RTLIL/RTLILOps.td"

#endif // CIRCT_DIALECT_RTLIL_RTLIL_TD
